version: "3.8"

services:
  paymentservice:
    image: harbor.lptdevops.website/online_boutique/paymentservice:latest
    container_name: paymentservice
    environment:
      - PORT=50050
      - DISABLE_PROFILER=1
    restart: always
    ports:
      - "50050:50050"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50050"]
      interval: 10s
      retries: 3
      start_period: 20s
      timeout: 5s
    networks:
      - online_boutique_network

networks:
  online_boutique_network:
    external: true
