version: "3.8"

services:
  productcatalogservice:
    image: harbor.lptdevops.website/online_boutique/productcatalogservice:latest
    container_name: productcatalogservice
    ports:
      - "3550:3550"
    environment:
      - PORT=3550
      - DISABLE_PROFILER=1
    restart: always
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:3550"]
      interval: 10s
      retries: 3
      start_period: 20s
      timeout: 5s
    networks:
      - online_boutique_network

networks:
  online_boutique_network:
    external: true

