version: "3.8"

services:
  shippingservice:
    image: thuanlp/online_boutique_shippingservice:latest
    container_name: shippingservice
    environment:
      - PORT=50051
      - DISABLE_PROFILER=1
    ports:
      - "50051:50051"
    restart: always
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 10s
      retries: 3
      start_period: 20s
      timeout: 5s
    networks:
      - online_boutique_network

networks:
  online_boutique_network:
    driver: bridge
