version: "3.8"

services:
  recommendationservice:
    image: thuanlp/online_boutique_recommendationservice:latest
    container_name: recommendationservice
    environment:
      - PORT=8088
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - DISABLE_PROFILER=1
    restart: always
    ports:
      - "8088:8088"
    container_name: recommendationservice
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:8088"]
      interval: 10s
      retries: 3
      start_period: 20s
      timeout: 5s
    networks:
      - online_boutique_network

networks:
  online_boutique_network:
    driver: bridge
