version: "3.8"

services:
  frontend:
    image: harbor.lptdevops.website/online_boutique/frontend:latest
    ports:
      - "80:80"
    restart: always
    environment:
      - PORT=80
      - ENABLE_PROFILER=0
      - ENABLE_TRACING=0
      - AD_SERVICE_ADDR=adservice:9555
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8088
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
    container_name: frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.224.140:80/_healthz"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    networks:
      - online_boutique_network

networks:
  online_boutique_network:
    external: true
