upstream my_servers {
    server 10.0.2.3:30080;
    server 10.0.2.4:30080;
    server 10.0.2.5:30080;
}

server {
    listen 80;
    server_name onlineshop.lptdevops.website;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name onlineshop.lptdevops.website;

    ssl_certificate /etc/letsencrypt/live/onlineshop.lptdevops.website/cert.pem;
    ssl_certificate_key /etc/letsencrypt/live/onlineshop.lptdevops.website/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://my_servers;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}